services:
  - type: web
    name: django-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi
    envVars:
      - key: DEBUG
        value: False
      - key: OPENAI_API_KEY
        sync: false