services:
  - type: web
    name: django-api
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn backend.wsgi:application --timeout 240"
    envVars:
      - key: DEBUG
        value: False
      - key: OPENAI_API_KEY
        sync: false
